[omdb]
api_key = "OMDB_API_KEY"

[database]
# Choisis le type de base : sqlite, postgresql ou duckdb
db_type = "sqlite"

# Nom de la base (ou fichier .db/.duckdb si SQLite ou DuckDB)
db_name = "ma_biblio"

# Ces champs sont ignorés si tu utilises SQLite ou DuckDB
db_user = "ton_utilisateur"
db_password = "ton_mot_de_passe"
db_host = "localhost"
db_port = "5432"
